# Generated by Django 4.1.7 on 2023-02-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('volume', models.IntegerField()),
            ],
            options={
                'db_table': 'financial_data',
            },
        ),
    ]
